### ISSUE TITLE
[Feature] Add Docker Compose Support

### ISSUE THREAD

**Issue by sangimed** [MatteoFasulo/Whisper-TikTok#42]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when setting up the development environment for the project. It involves multiple steps to ensure all dependencies are installed correctly and that the application runs consistently across different systems.

**Describe the solution you'd like**
I would like to add Docker Compose support to the project. Docker Compose simplifies the setup process by allowing the application to be started with a single command (docker-compose up). This will handle the build and runtime configurations, ensuring a consistent environment for all developers.

**Describe alternatives you've considered**
An alternative solution is to provide detailed setup instructions for developers to manually install dependencies and configure the environment. However, this approach can lead to inconsistencies and is more error-prone compared to using Docker Compose.

**Additional context**
Here is a proposed docker-compose.yml file that can be added to the root of the project:
```yml
version: '3.8'

services:
  whisper-tiktok:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - .:/app

```
This configuration file will:

This configuration file will:

- Build the Docker image using the provided Dockerfile.
- Map port 8501 from the host to the container, making the application accessible at http://localhost:8501.
- Include a health check to monitor the application's health status.
- Mount the current directory to /app inside the container to facilitate live updates to the code without rebuilding the image.
